### ISSUE TITLE
share最新的版本是1.0还是2.0

### ISSUE THREAD

**Issue by 1500256797** [zhangjh/share-lib#1]
我看最新的chatgpt-starter用的是2.0  maven上是1.0

**Comment by zhangjh** [comment]
最新是2.0.x，你说的maven上是1.0请问地址是什么？如果不是中央仓库可能是镜像同步延迟

**Comment by zhangjh** [comment]
![image](https://user-images.githubusercontent.com/3371714/226088394-dc15622f-4b5e-461c-bec8-dc2582d0f27c.png)
maven中央仓库查询截图
https://central.sonatype.com/
